unstable_features = true

max_width = 150

# Выравнивание комментариев
struct_field_align_threshold = 120

# Если хочешь, чтобы выравнивание работало и для перечислений (enum)
enum_discrim_align_threshold = 20

# Разрешает писать if/else в одну строку, если они короткие
if_else_single_line = true

# Позволяет объединять простые блоки кода в одну строку
single_line_if_else_max_width = 80

# (Опционально) Аналогично для простых match, если они очень короткие
match_arm_blocks = false

# Всегда ставить запятую после ветки `match`, даже если там есть блоки `{}`. Это уменьшает количество «шумных» изменений в Git при добавлении новых веток.
match_block_trailing_comma = true

# Устанавливает максимальное количество пустых строк подряд
# Например, если хочешь разрешить до 2 строк:
blank_lines_upper_bound = 2

# Оставляем цепочку разбитой, если она превышает этот порог.
# Если поставить маленькое число (например, 20),
# то почти любая цепочка будет оставаться многострочной.
chain_width = 40

# А эта опция (только для Nightly) заставляет rustfmt
# всегда переносить точку на новую строку, если цепочка разбита.
indent_style = "Block"